Update README.md
napsternxg/awesome-scholarly-data-analysis pull request #10
Opened 2019-04-04 21:31 UTC by michaelfaerber

2019-04-05 01:01 UTC, napsternxg commented
@michaelfaerber thanks. Can you provide details about the Pull Request?

2019-04-05 19:31 UTC, michaelfaerber commented
I'll to contribute to the awesome list of data sets by adding the data sets (1) Microsoft Academic Knowledge Graph (http://ma-graph.org/), (2) arXiv CS dataset (http://citation-recommendation.org/publications), and (3) unarXiv (https://github.com/IllDepence/unarXive).

2019-04-05 20:42 UTC, napsternxg requested changes
@michaelfaerber thanks a lot, these are all very exciting resources. 
I have made some comments about arranging the links. Can you do that?

2019-04-05 20:42 UTC, napsternxg commented on README.md
> +* [Microsoft Academic Knowledge Graph](http://ma-graph.org/)
Can you change the name of Microsoft Academic Knowledge Graph to Microsoft Academic Graph - RDF dump as we already have MAG at the top. Another option is to add a separate link next to MAG with title RDF triples.

2019-04-05 20:42 UTC, napsternxg commented on README.md
> +* [arXiv CS dataset](http://citation-recommendation.org/publications/#A_High-Quality_Gold_Standard_for_Citation-based_Tasks)
For arXiv CS dataset, rename it to arXiv CS citation in context, may be put it under `Information Extraction and NLP`

2019-04-05 20:42 UTC, napsternxg commented on README.md
> +* [arXiv fulltext + citations dataset](https://github.com/IllDepence/unarXive)
Keep this but change the link to the zenodo page: https://zenodo.org/record/2609187#.XKe86JhKh3g

For the code also add an entry for the `unarXiv (Citation in context from arXiv)` put it under `Tools > Citation and metadata extraction`. 
Also, keep the original but link to the zenodo page:

2019-10-23 17:51 UTC, napsternxg commented
I have resolved the changes and am merging these. 
Thanks for the links @michaelfaerber

2019-10-23 17:54 UTC, merged