List updated with suggestions by Ali
napsternxg/awesome-scholarly-data-analysis pull request #8
Opened 2019-02-21 12:40 UTC by akbaritabar

I have tried to add R packages, python libraries, conferences and events, scientific community and associations, and citation and metadata extraction tools and libraries to improve this great initiative a bit. Feel free to check my changes and revise them if necessary

2019-02-21 17:53 UTC, napsternxg requested changes
I have suggested some changes. 

I think we can remove Code section and move it inside tools under proper heading. 
Distinction in python or R can be skipped. or maybe add a small text next to it to indicate if it is Python or R.

2019-02-21 17:53 UTC, napsternxg commented on README.md
> +* [Science Parse](https://github.com/allenai/science-parse)
This is a duplicate from Code.

2019-02-21 21:40 UTC, akbaritabar commented
I tried to apply your kind suggestions, I hope I haven't miss something, please check.
I removed code section and brought its subjects to other sections. I put in parentheses a note if the library is for R or Python. Also I added "& Analysis" to the this title "User interface to publication datasets & analysis" in "Tools" section to allow moving some subjects under it. 

Please control these to be in line with your suggestions and the main goals of list.

2019-02-21 23:17 UTC, napsternxg approved these changes
Looks great. Thanks a lot.

2019-02-21 23:18 UTC, napsternxg commented
@akbaritabar can you resolve the conflicts and then update the PR. You will need to resync your repo with my master. I made a few changes on my repo.

2019-02-22 17:07 UTC, merged

2019-02-22 21:05 UTC, akbaritabar commented
Thank you dear @napsternxg for handling the conflicts, and sorry for my delay. I had a hectic day at work.